import { Component, inject } from '@angular/core';
import { SummaryPage } from '../../../interfaces/summary-page';
import { RouterLink, Router } from '@angular/router';
import { Title } from '@angular/platform-browser';
import { FooterComponent } from '../../footer/footer.component';

@Component({
  selector: 'app-summary',
  standalone: true,
  imports: [RouterLink, FooterComponent],
  templateUrl: './summary.component.html',
  styleUrl: './summary.component.sass'
})
export class SummaryComponent {

  summary: SummaryPage[];
  private router: Router = inject(Router);

  constructor() {
    this.summary = [
      {
        id: 1,
        title: 'Introduction',
        subtitle: [
          {
            id: 1,
            title: 'Introduction section 1',
            contenu: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi quis mi id quam sodales congue non vitae est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget fermentum elit. Mauris turpis sem, luctus id quam nec, faucibus imperdiet quam. Aenean ex lectus, ultrices eu gravida eu, placerat vitae metus. Cras libero elit, hendrerit eget rhoncus ac, sollicitudin ac ligula. Phasellus nec faucibus diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam ultricies lorem commodo nibh hendrerit gravida. Suspendisse interdum fringilla aliquet. Quisque malesuada ultrices eros, at gravida leo semper sed. Vivamus ac mattis sapien. Praesent nec leo volutpat elit facilisis iaculis vel ac eros. Donec euismod velit quis dolor auctor pharetra. Vestibulum congue accumsan sem, vel euismod lectus convallis eu. Vivamus quis enim diam. Fusce laoreet varius neque non laoreet. Etiam cursus lobortis nibh, vel efficitur magna convallis ac. Phasellus leo sapien, vehicula eu nibh vitae, tincidunt vulputate tellus. Sed faucibus placerat risus, eu malesuada nibh molestie sit amet. Nunc vitae luctus mauris, sed bibendum tellus. Ut imperdiet justo ut purus suscipit feugiat. Morbi ac nisl quis leo fringilla convallis vitae id enim. Nunc congue dolor nisl, non semper orci euismod non. Ut congue nibh id libero tincidunt, ac placerat libero finibus. Praesent non massa nisl. In a turpis varius odio sodales facilisis."
          },
          {
            id: 2,
            title: 'Introduction section 2',
            contenu: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi quis mi id quam sodales congue non vitae est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget fermentum elit. Mauris turpis sem, luctus id quam nec, faucibus imperdiet quam. Aenean ex lectus, ultrices eu gravida eu, placerat vitae metus. Cras libero elit, hendrerit eget rhoncus ac, sollicitudin ac ligula. Phasellus nec faucibus diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam ultricies lorem commodo nibh hendrerit gravida. Suspendisse interdum fringilla aliquet. Quisque malesuada ultrices eros, at gravida leo semper sed. Vivamus ac mattis sapien. Praesent nec leo volutpat elit facilisis iaculis vel ac eros. Donec euismod velit quis dolor auctor pharetra. Vestibulum congue accumsan sem, vel euismod lectus convallis eu. Vivamus quis enim diam. Fusce laoreet varius neque non laoreet. Etiam cursus lobortis nibh, vel efficitur magna convallis ac. Phasellus leo sapien, vehicula eu nibh vitae, tincidunt vulputate tellus. Sed faucibus placerat risus, eu malesuada nibh molestie sit amet. Nunc vitae luctus mauris, sed bibendum tellus. Ut imperdiet justo ut purus suscipit feugiat. Morbi ac nisl quis leo fringilla convallis vitae id enim. Nunc congue dolor nisl, non semper orci euismod non. Ut congue nibh id libero tincidunt, ac placerat libero finibus. Praesent non massa nisl. In a turpis varius odio sodales facilisis."
          },
          {
            id: 3,
            title: 'Introduction section 3',
            contenu: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi quis mi id quam sodales congue non vitae est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget fermentum elit. Mauris turpis sem, luctus id quam nec, faucibus imperdiet quam. Aenean ex lectus, ultrices eu gravida eu, placerat vitae metus. Cras libero elit, hendrerit eget rhoncus ac, sollicitudin ac ligula. Phasellus nec faucibus diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam ultricies lorem commodo nibh hendrerit gravida. Suspendisse interdum fringilla aliquet. Quisque malesuada ultrices eros, at gravida leo semper sed. Vivamus ac mattis sapien. Praesent nec leo volutpat elit facilisis iaculis vel ac eros. Donec euismod velit quis dolor auctor pharetra. Vestibulum congue accumsan sem, vel euismod lectus convallis eu. Vivamus quis enim diam. Fusce laoreet varius neque non laoreet. Etiam cursus lobortis nibh, vel efficitur magna convallis ac. Phasellus leo sapien, vehicula eu nibh vitae, tincidunt vulputate tellus. Sed faucibus placerat risus, eu malesuada nibh molestie sit amet. Nunc vitae luctus mauris, sed bibendum tellus. Ut imperdiet justo ut purus suscipit feugiat. Morbi ac nisl quis leo fringilla convallis vitae id enim. Nunc congue dolor nisl, non semper orci euismod non. Ut congue nibh id libero tincidunt, ac placerat libero finibus. Praesent non massa nisl. In a turpis varius odio sodales facilisis."
          },
        ]
      },
      {
        id: 2,
        title: 'Chapter 1',
        subtitle: [
          {
            id: 1,
            title: 'Chapter section 1',
            contenu: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi quis mi id quam sodales congue non vitae est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget fermentum elit. Mauris turpis sem, luctus id quam nec, faucibus imperdiet quam. Aenean ex lectus, ultrices eu gravida eu, placerat vitae metus. Cras libero elit, hendrerit eget rhoncus ac, sollicitudin ac ligula. Phasellus nec faucibus diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam ultricies lorem commodo nibh hendrerit gravida. Suspendisse interdum fringilla aliquet. Quisque malesuada ultrices eros, at gravida leo semper sed. Vivamus ac mattis sapien. Praesent nec leo volutpat elit facilisis iaculis vel ac eros. Donec euismod velit quis dolor auctor pharetra. Vestibulum congue accumsan sem, vel euismod lectus convallis eu. Vivamus quis enim diam. Fusce laoreet varius neque non laoreet. Etiam cursus lobortis nibh, vel efficitur magna convallis ac. Phasellus leo sapien, vehicula eu nibh vitae, tincidunt vulputate tellus. Sed faucibus placerat risus, eu malesuada nibh molestie sit amet. Nunc vitae luctus mauris, sed bibendum tellus. Ut imperdiet justo ut purus suscipit feugiat. Morbi ac nisl quis leo fringilla convallis vitae id enim. Nunc congue dolor nisl, non semper orci euismod non. Ut congue nibh id libero tincidunt, ac placerat libero finibus. Praesent non massa nisl. In a turpis varius odio sodales facilisis."
          },
          {
            id: 2,
            title: 'Chapter section 2',
            contenu: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi quis mi id quam sodales congue non vitae est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget fermentum elit. Mauris turpis sem, luctus id quam nec, faucibus imperdiet quam. Aenean ex lectus, ultrices eu gravida eu, placerat vitae metus. Cras libero elit, hendrerit eget rhoncus ac, sollicitudin ac ligula. Phasellus nec faucibus diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam ultricies lorem commodo nibh hendrerit gravida. Suspendisse interdum fringilla aliquet. Quisque malesuada ultrices eros, at gravida leo semper sed. Vivamus ac mattis sapien. Praesent nec leo volutpat elit facilisis iaculis vel ac eros. Donec euismod velit quis dolor auctor pharetra. Vestibulum congue accumsan sem, vel euismod lectus convallis eu. Vivamus quis enim diam. Fusce laoreet varius neque non laoreet. Etiam cursus lobortis nibh, vel efficitur magna convallis ac. Phasellus leo sapien, vehicula eu nibh vitae, tincidunt vulputate tellus. Sed faucibus placerat risus, eu malesuada nibh molestie sit amet. Nunc vitae luctus mauris, sed bibendum tellus. Ut imperdiet justo ut purus suscipit feugiat. Morbi ac nisl quis leo fringilla convallis vitae id enim. Nunc congue dolor nisl, non semper orci euismod non. Ut congue nibh id libero tincidunt, ac placerat libero finibus. Praesent non massa nisl. In a turpis varius odio sodales facilisis."
          },
          {
            id: 3,
            title: 'Chapter section 3',
            contenu: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi quis mi id quam sodales congue non vitae est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget fermentum elit. Mauris turpis sem, luctus id quam nec, faucibus imperdiet quam. Aenean ex lectus, ultrices eu gravida eu, placerat vitae metus. Cras libero elit, hendrerit eget rhoncus ac, sollicitudin ac ligula. Phasellus nec faucibus diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam ultricies lorem commodo nibh hendrerit gravida. Suspendisse interdum fringilla aliquet. Quisque malesuada ultrices eros, at gravida leo semper sed. Vivamus ac mattis sapien. Praesent nec leo volutpat elit facilisis iaculis vel ac eros. Donec euismod velit quis dolor auctor pharetra. Vestibulum congue accumsan sem, vel euismod lectus convallis eu. Vivamus quis enim diam. Fusce laoreet varius neque non laoreet. Etiam cursus lobortis nibh, vel efficitur magna convallis ac. Phasellus leo sapien, vehicula eu nibh vitae, tincidunt vulputate tellus. Sed faucibus placerat risus, eu malesuada nibh molestie sit amet. Nunc vitae luctus mauris, sed bibendum tellus. Ut imperdiet justo ut purus suscipit feugiat. Morbi ac nisl quis leo fringilla convallis vitae id enim. Nunc congue dolor nisl, non semper orci euismod non. Ut congue nibh id libero tincidunt, ac placerat libero finibus. Praesent non massa nisl. In a turpis varius odio sodales facilisis."
          },
          {
            id: 4,
            title: 'Chapter section 4',
            contenu: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi quis mi id quam sodales congue non vitae est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget fermentum elit. Mauris turpis sem, luctus id quam nec, faucibus imperdiet quam. Aenean ex lectus, ultrices eu gravida eu, placerat vitae metus. Cras libero elit, hendrerit eget rhoncus ac, sollicitudin ac ligula. Phasellus nec faucibus diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam ultricies lorem commodo nibh hendrerit gravida. Suspendisse interdum fringilla aliquet. Quisque malesuada ultrices eros, at gravida leo semper sed. Vivamus ac mattis sapien. Praesent nec leo volutpat elit facilisis iaculis vel ac eros. Donec euismod velit quis dolor auctor pharetra. Vestibulum congue accumsan sem, vel euismod lectus convallis eu. Vivamus quis enim diam. Fusce laoreet varius neque non laoreet. Etiam cursus lobortis nibh, vel efficitur magna convallis ac. Phasellus leo sapien, vehicula eu nibh vitae, tincidunt vulputate tellus. Sed faucibus placerat risus, eu malesuada nibh molestie sit amet. Nunc vitae luctus mauris, sed bibendum tellus. Ut imperdiet justo ut purus suscipit feugiat. Morbi ac nisl quis leo fringilla convallis vitae id enim. Nunc congue dolor nisl, non semper orci euismod non. Ut congue nibh id libero tincidunt, ac placerat libero finibus. Praesent non massa nisl. In a turpis varius odio sodales facilisis."
          },
          {
            id: 5,
            title: 'Chapter section 5',
            contenu: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi quis mi id quam sodales congue non vitae est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget fermentum elit. Mauris turpis sem, luctus id quam nec, faucibus imperdiet quam. Aenean ex lectus, ultrices eu gravida eu, placerat vitae metus. Cras libero elit, hendrerit eget rhoncus ac, sollicitudin ac ligula. Phasellus nec faucibus diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam ultricies lorem commodo nibh hendrerit gravida. Suspendisse interdum fringilla aliquet. Quisque malesuada ultrices eros, at gravida leo semper sed. Vivamus ac mattis sapien. Praesent nec leo volutpat elit facilisis iaculis vel ac eros. Donec euismod velit quis dolor auctor pharetra. Vestibulum congue accumsan sem, vel euismod lectus convallis eu. Vivamus quis enim diam. Fusce laoreet varius neque non laoreet. Etiam cursus lobortis nibh, vel efficitur magna convallis ac. Phasellus leo sapien, vehicula eu nibh vitae, tincidunt vulputate tellus. Sed faucibus placerat risus, eu malesuada nibh molestie sit amet. Nunc vitae luctus mauris, sed bibendum tellus. Ut imperdiet justo ut purus suscipit feugiat. Morbi ac nisl quis leo fringilla convallis vitae id enim. Nunc congue dolor nisl, non semper orci euismod non. Ut congue nibh id libero tincidunt, ac placerat libero finibus. Praesent non massa nisl. In a turpis varius odio sodales facilisis."
          },
        ]
      },
      {
        id: 3,
        title: 'Chapter 2',
        subtitle: [{
          id: 1,
          title: 'Chapter section 1',
          contenu: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi quis mi id quam sodales congue non vitae est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget fermentum elit. Mauris turpis sem, luctus id quam nec, faucibus imperdiet quam. Aenean ex lectus, ultrices eu gravida eu, placerat vitae metus. Cras libero elit, hendrerit eget rhoncus ac, sollicitudin ac ligula. Phasellus nec faucibus diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam ultricies lorem commodo nibh hendrerit gravida. Suspendisse interdum fringilla aliquet. Quisque malesuada ultrices eros, at gravida leo semper sed. Vivamus ac mattis sapien. Praesent nec leo volutpat elit facilisis iaculis vel ac eros. Donec euismod velit quis dolor auctor pharetra. Vestibulum congue accumsan sem, vel euismod lectus convallis eu. Vivamus quis enim diam. Fusce laoreet varius neque non laoreet. Etiam cursus lobortis nibh, vel efficitur magna convallis ac. Phasellus leo sapien, vehicula eu nibh vitae, tincidunt vulputate tellus. Sed faucibus placerat risus, eu malesuada nibh molestie sit amet. Nunc vitae luctus mauris, sed bibendum tellus. Ut imperdiet justo ut purus suscipit feugiat. Morbi ac nisl quis leo fringilla convallis vitae id enim. Nunc congue dolor nisl, non semper orci euismod non. Ut congue nibh id libero tincidunt, ac placerat libero finibus. Praesent non massa nisl. In a turpis varius odio sodales facilisis."
        },
        {
          id: 2,
          title: 'Chapter section 2',
          contenu: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi quis mi id quam sodales congue non vitae est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget fermentum elit. Mauris turpis sem, luctus id quam nec, faucibus imperdiet quam. Aenean ex lectus, ultrices eu gravida eu, placerat vitae metus. Cras libero elit, hendrerit eget rhoncus ac, sollicitudin ac ligula. Phasellus nec faucibus diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam ultricies lorem commodo nibh hendrerit gravida. Suspendisse interdum fringilla aliquet. Quisque malesuada ultrices eros, at gravida leo semper sed. Vivamus ac mattis sapien. Praesent nec leo volutpat elit facilisis iaculis vel ac eros. Donec euismod velit quis dolor auctor pharetra. Vestibulum congue accumsan sem, vel euismod lectus convallis eu. Vivamus quis enim diam. Fusce laoreet varius neque non laoreet. Etiam cursus lobortis nibh, vel efficitur magna convallis ac. Phasellus leo sapien, vehicula eu nibh vitae, tincidunt vulputate tellus. Sed faucibus placerat risus, eu malesuada nibh molestie sit amet. Nunc vitae luctus mauris, sed bibendum tellus. Ut imperdiet justo ut purus suscipit feugiat. Morbi ac nisl quis leo fringilla convallis vitae id enim. Nunc congue dolor nisl, non semper orci euismod non. Ut congue nibh id libero tincidunt, ac placerat libero finibus. Praesent non massa nisl. In a turpis varius odio sodales facilisis."
        },
        {
          id: 3,
          title: 'Chapter section 3',
          contenu: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi quis mi id quam sodales congue non vitae est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget fermentum elit. Mauris turpis sem, luctus id quam nec, faucibus imperdiet quam. Aenean ex lectus, ultrices eu gravida eu, placerat vitae metus. Cras libero elit, hendrerit eget rhoncus ac, sollicitudin ac ligula. Phasellus nec faucibus diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam ultricies lorem commodo nibh hendrerit gravida. Suspendisse interdum fringilla aliquet. Quisque malesuada ultrices eros, at gravida leo semper sed. Vivamus ac mattis sapien. Praesent nec leo volutpat elit facilisis iaculis vel ac eros. Donec euismod velit quis dolor auctor pharetra. Vestibulum congue accumsan sem, vel euismod lectus convallis eu. Vivamus quis enim diam. Fusce laoreet varius neque non laoreet. Etiam cursus lobortis nibh, vel efficitur magna convallis ac. Phasellus leo sapien, vehicula eu nibh vitae, tincidunt vulputate tellus. Sed faucibus placerat risus, eu malesuada nibh molestie sit amet. Nunc vitae luctus mauris, sed bibendum tellus. Ut imperdiet justo ut purus suscipit feugiat. Morbi ac nisl quis leo fringilla convallis vitae id enim. Nunc congue dolor nisl, non semper orci euismod non. Ut congue nibh id libero tincidunt, ac placerat libero finibus. Praesent non massa nisl. In a turpis varius odio sodales facilisis."
        }
        ]
      },
      {
        id: 4,
        title: 'Chapter 3',
        subtitle: [
          {
            id: 1,
            title: 'Chapter section 1',
            contenu: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi quis mi id quam sodales congue non vitae est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget fermentum elit. Mauris turpis sem, luctus id quam nec, faucibus imperdiet quam. Aenean ex lectus, ultrices eu gravida eu, placerat vitae metus. Cras libero elit, hendrerit eget rhoncus ac, sollicitudin ac ligula. Phasellus nec faucibus diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam ultricies lorem commodo nibh hendrerit gravida. Suspendisse interdum fringilla aliquet. Quisque malesuada ultrices eros, at gravida leo semper sed. Vivamus ac mattis sapien. Praesent nec leo volutpat elit facilisis iaculis vel ac eros. Donec euismod velit quis dolor auctor pharetra. Vestibulum congue accumsan sem, vel euismod lectus convallis eu. Vivamus quis enim diam. Fusce laoreet varius neque non laoreet. Etiam cursus lobortis nibh, vel efficitur magna convallis ac. Phasellus leo sapien, vehicula eu nibh vitae, tincidunt vulputate tellus. Sed faucibus placerat risus, eu malesuada nibh molestie sit amet. Nunc vitae luctus mauris, sed bibendum tellus. Ut imperdiet justo ut purus suscipit feugiat. Morbi ac nisl quis leo fringilla convallis vitae id enim. Nunc congue dolor nisl, non semper orci euismod non. Ut congue nibh id libero tincidunt, ac placerat libero finibus. Praesent non massa nisl. In a turpis varius odio sodales facilisis."
          },
          {
            id: 2,
            title: 'Chapter section 2',
            contenu: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi quis mi id quam sodales congue non vitae est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget fermentum elit. Mauris turpis sem, luctus id quam nec, faucibus imperdiet quam. Aenean ex lectus, ultrices eu gravida eu, placerat vitae metus. Cras libero elit, hendrerit eget rhoncus ac, sollicitudin ac ligula. Phasellus nec faucibus diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam ultricies lorem commodo nibh hendrerit gravida. Suspendisse interdum fringilla aliquet. Quisque malesuada ultrices eros, at gravida leo semper sed. Vivamus ac mattis sapien. Praesent nec leo volutpat elit facilisis iaculis vel ac eros. Donec euismod velit quis dolor auctor pharetra. Vestibulum congue accumsan sem, vel euismod lectus convallis eu. Vivamus quis enim diam. Fusce laoreet varius neque non laoreet. Etiam cursus lobortis nibh, vel efficitur magna convallis ac. Phasellus leo sapien, vehicula eu nibh vitae, tincidunt vulputate tellus. Sed faucibus placerat risus, eu malesuada nibh molestie sit amet. Nunc vitae luctus mauris, sed bibendum tellus. Ut imperdiet justo ut purus suscipit feugiat. Morbi ac nisl quis leo fringilla convallis vitae id enim. Nunc congue dolor nisl, non semper orci euismod non. Ut congue nibh id libero tincidunt, ac placerat libero finibus. Praesent non massa nisl. In a turpis varius odio sodales facilisis."
          },
          {
            id: 3,
            title: 'Chapter section 3',
            contenu: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi quis mi id quam sodales congue non vitae est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget fermentum elit. Mauris turpis sem, luctus id quam nec, faucibus imperdiet quam. Aenean ex lectus, ultrices eu gravida eu, placerat vitae metus. Cras libero elit, hendrerit eget rhoncus ac, sollicitudin ac ligula. Phasellus nec faucibus diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam ultricies lorem commodo nibh hendrerit gravida. Suspendisse interdum fringilla aliquet. Quisque malesuada ultrices eros, at gravida leo semper sed. Vivamus ac mattis sapien. Praesent nec leo volutpat elit facilisis iaculis vel ac eros. Donec euismod velit quis dolor auctor pharetra. Vestibulum congue accumsan sem, vel euismod lectus convallis eu. Vivamus quis enim diam. Fusce laoreet varius neque non laoreet. Etiam cursus lobortis nibh, vel efficitur magna convallis ac. Phasellus leo sapien, vehicula eu nibh vitae, tincidunt vulputate tellus. Sed faucibus placerat risus, eu malesuada nibh molestie sit amet. Nunc vitae luctus mauris, sed bibendum tellus. Ut imperdiet justo ut purus suscipit feugiat. Morbi ac nisl quis leo fringilla convallis vitae id enim. Nunc congue dolor nisl, non semper orci euismod non. Ut congue nibh id libero tincidunt, ac placerat libero finibus. Praesent non massa nisl. In a turpis varius odio sodales facilisis."
          },
          {
            id: 4,
            title: 'Chapter section 4',
            contenu: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi quis mi id quam sodales congue non vitae est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget fermentum elit. Mauris turpis sem, luctus id quam nec, faucibus imperdiet quam. Aenean ex lectus, ultrices eu gravida eu, placerat vitae metus. Cras libero elit, hendrerit eget rhoncus ac, sollicitudin ac ligula. Phasellus nec faucibus diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam ultricies lorem commodo nibh hendrerit gravida. Suspendisse interdum fringilla aliquet. Quisque malesuada ultrices eros, at gravida leo semper sed. Vivamus ac mattis sapien. Praesent nec leo volutpat elit facilisis iaculis vel ac eros. Donec euismod velit quis dolor auctor pharetra. Vestibulum congue accumsan sem, vel euismod lectus convallis eu. Vivamus quis enim diam. Fusce laoreet varius neque non laoreet. Etiam cursus lobortis nibh, vel efficitur magna convallis ac. Phasellus leo sapien, vehicula eu nibh vitae, tincidunt vulputate tellus. Sed faucibus placerat risus, eu malesuada nibh molestie sit amet. Nunc vitae luctus mauris, sed bibendum tellus. Ut imperdiet justo ut purus suscipit feugiat. Morbi ac nisl quis leo fringilla convallis vitae id enim. Nunc congue dolor nisl, non semper orci euismod non. Ut congue nibh id libero tincidunt, ac placerat libero finibus. Praesent non massa nisl. In a turpis varius odio sodales facilisis."
          },
          {
            id: 5,
            title: 'Chapter section 5',
            contenu: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi quis mi id quam sodales congue non vitae est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget fermentum elit. Mauris turpis sem, luctus id quam nec, faucibus imperdiet quam. Aenean ex lectus, ultrices eu gravida eu, placerat vitae metus. Cras libero elit, hendrerit eget rhoncus ac, sollicitudin ac ligula. Phasellus nec faucibus diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam ultricies lorem commodo nibh hendrerit gravida. Suspendisse interdum fringilla aliquet. Quisque malesuada ultrices eros, at gravida leo semper sed. Vivamus ac mattis sapien. Praesent nec leo volutpat elit facilisis iaculis vel ac eros. Donec euismod velit quis dolor auctor pharetra. Vestibulum congue accumsan sem, vel euismod lectus convallis eu. Vivamus quis enim diam. Fusce laoreet varius neque non laoreet. Etiam cursus lobortis nibh, vel efficitur magna convallis ac. Phasellus leo sapien, vehicula eu nibh vitae, tincidunt vulputate tellus. Sed faucibus placerat risus, eu malesuada nibh molestie sit amet. Nunc vitae luctus mauris, sed bibendum tellus. Ut imperdiet justo ut purus suscipit feugiat. Morbi ac nisl quis leo fringilla convallis vitae id enim. Nunc congue dolor nisl, non semper orci euismod non. Ut congue nibh id libero tincidunt, ac placerat libero finibus. Praesent non massa nisl. In a turpis varius odio sodales facilisis."
          },
          {
            id: 6,
            title: 'Chapter section 6',
            contenu: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi quis mi id quam sodales congue non vitae est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget fermentum elit. Mauris turpis sem, luctus id quam nec, faucibus imperdiet quam. Aenean ex lectus, ultrices eu gravida eu, placerat vitae metus. Cras libero elit, hendrerit eget rhoncus ac, sollicitudin ac ligula. Phasellus nec faucibus diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam ultricies lorem commodo nibh hendrerit gravida. Suspendisse interdum fringilla aliquet. Quisque malesuada ultrices eros, at gravida leo semper sed. Vivamus ac mattis sapien. Praesent nec leo volutpat elit facilisis iaculis vel ac eros. Donec euismod velit quis dolor auctor pharetra. Vestibulum congue accumsan sem, vel euismod lectus convallis eu. Vivamus quis enim diam. Fusce laoreet varius neque non laoreet. Etiam cursus lobortis nibh, vel efficitur magna convallis ac. Phasellus leo sapien, vehicula eu nibh vitae, tincidunt vulputate tellus. Sed faucibus placerat risus, eu malesuada nibh molestie sit amet. Nunc vitae luctus mauris, sed bibendum tellus. Ut imperdiet justo ut purus suscipit feugiat. Morbi ac nisl quis leo fringilla convallis vitae id enim. Nunc congue dolor nisl, non semper orci euismod non. Ut congue nibh id libero tincidunt, ac placerat libero finibus. Praesent non massa nisl. In a turpis varius odio sodales facilisis."
          },
          {
            id: 7,
            title: 'Chapter section 7',
            contenu: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi quis mi id quam sodales congue non vitae est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget fermentum elit. Mauris turpis sem, luctus id quam nec, faucibus imperdiet quam. Aenean ex lectus, ultrices eu gravida eu, placerat vitae metus. Cras libero elit, hendrerit eget rhoncus ac, sollicitudin ac ligula. Phasellus nec faucibus diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam ultricies lorem commodo nibh hendrerit gravida. Suspendisse interdum fringilla aliquet. Quisque malesuada ultrices eros, at gravida leo semper sed. Vivamus ac mattis sapien. Praesent nec leo volutpat elit facilisis iaculis vel ac eros. Donec euismod velit quis dolor auctor pharetra. Vestibulum congue accumsan sem, vel euismod lectus convallis eu. Vivamus quis enim diam. Fusce laoreet varius neque non laoreet. Etiam cursus lobortis nibh, vel efficitur magna convallis ac. Phasellus leo sapien, vehicula eu nibh vitae, tincidunt vulputate tellus. Sed faucibus placerat risus, eu malesuada nibh molestie sit amet. Nunc vitae luctus mauris, sed bibendum tellus. Ut imperdiet justo ut purus suscipit feugiat. Morbi ac nisl quis leo fringilla convallis vitae id enim. Nunc congue dolor nisl, non semper orci euismod non. Ut congue nibh id libero tincidunt, ac placerat libero finibus. Praesent non massa nisl. In a turpis varius odio sodales facilisis."
          }
        ]
      }
    ]
  }

  actualRoute() {
    return this.router.url.split('#')[0];
  }


}
